"""empty message

Revision ID: 164f741b4f86
Revises: e1090194b804
Create Date: 2017-12-10 14:36:54.873024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164f741b4f86'
down_revision = 'e1090194b804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
