"""empty message

Revision ID: 213d3d99dadb
Revises: 6038a29bf985
Create Date: 2017-12-19 11:54:13.638224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d3d99dadb'
down_revision = '6038a29bf985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_date')
    # ### end Alembic commands ###
