"""empty message

Revision ID: 2ce3c09a55ac
Revises: 54981b6292f4
Create Date: 2018-03-29 15:48:01.010020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce3c09a55ac'
down_revision = '54981b6292f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'book', ['name'], unique=True)
    # ### end Alembic commands ###
