"""empty message

Revision ID: 4ce46ee217f8
Revises: 7346525ea87e
Create Date: 2018-04-29 22:31:11.441687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce46ee217f8'
down_revision = '7346525ea87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'tag_id')
    # ### end Alembic commands ###
