"""empty message

Revision ID: 4de3c2fa925a
Revises: 6cee23d74aeb
Create Date: 2017-12-17 16:14:17.845388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de3c2fa925a'
down_revision = '6cee23d74aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('qq_num', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'qq_num')
    # ### end Alembic commands ###
