"""empty message

Revision ID: 54981b6292f4
Revises: e8cf9e2daef9
Create Date: 2018-03-29 15:28:45.322933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54981b6292f4'
down_revision = 'e8cf9e2daef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###
