"""empty message

Revision ID: 582cf774aac6
Revises: e13b6015b51b
Create Date: 2018-04-23 22:09:55.480602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '582cf774aac6'
down_revision = 'e13b6015b51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('comment', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('test', mysql.TEXT(), nullable=True))
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
