"""empty message

Revision ID: 60280321a70b
Revises: 00c7612a3fb6
Create Date: 2018-04-29 22:18:58.571432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60280321a70b'
down_revision = '00c7612a3fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'post_id')
    # ### end Alembic commands ###
