"""empty message

Revision ID: 6cee23d74aeb
Revises: 7f89099965a8
Create Date: 2017-12-13 22:03:35.249030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cee23d74aeb'
down_revision = '7f89099965a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('head_portrait', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'head_portrait')
    # ### end Alembic commands ###
