"""empty message

Revision ID: 7346525ea87e
Revises: 60280321a70b
Create Date: 2018-04-29 22:19:25.999408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7346525ea87e'
down_revision = '60280321a70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_2', 'category', type_='foreignkey')
    op.drop_column('category', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('category_ibfk_2', 'category', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
