"""empty message

Revision ID: abbfc81f65a9
Revises: d361cb6f8095
Create Date: 2018-02-24 15:38:40.167296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbfc81f65a9'
down_revision = 'd361cb6f8095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'book_id')
    # ### end Alembic commands ###
