"""empty message

Revision ID: c748137fd77c
Revises: 4de3c2fa925a
Create Date: 2017-12-17 16:17:31.791097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c748137fd77c'
down_revision = '4de3c2fa925a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('introduction', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'introduction')
    # ### end Alembic commands ###
