"""empty message

Revision ID: c81bb11e2746
Revises: 24f37b5bba6c
Create Date: 2017-12-11 16:54:26.505976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c81bb11e2746'
down_revision = '24f37b5bba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tag_ibfk_1', 'tag', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
